# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: UK TV Guide
version: "0.2"
slug: uktvguide
description: UK TV Guide
url: "https://github.com/uk-james/Home-Assistant-UK-TV-Guide/tree/main/tvguide"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world!.."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
